permalink: /blog/:year/:month/:day/:title
markdown: kramdown
github_username: nickebbitt
twitter_username: nickebbitt
linkedin_username: nickebbitt
stackoverflow_username: 2323210/nickebbitt
google_analytics: UA-88224505-1
future: true
plugins:
  - jekyll-redirect-from
  - jekyll-feed
whitelist:
  - jekyll-redirect-from

