# Site settings
title: Software development and that!
description: > # this means to ignore newlines until "baseurl:"
  This site hosts my development blog, CV and general info about things I'm up to.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://nickebbitt.github.io" # the base hostname & protocol for your site
twitter_username: nickebbitt
github_username:  nickebbitt

# Build settings
markdown: kramdown
